website = 'https://www.weforum.org/partners#search'
partners_type_xpath = '(//div[@class="organisation-search__filter-group__content"])[1]/ul/li/a'
org_hlinks_xpath = '//div[@class="organisation-search__groups"]/div/div/div/a'
org_name_xpath = '//h1[@class="organization__name"]'
organization_description_xpath = '//div[@class="organization__description"]/p'
organization_headquarters_xpath = '//dl[@class="column organization__profile__stats"]/dd'
organization_site_xpath = '//a[@class="organization__website--dark"]'
organization_file = 'organizations.csv'
links_file = 'orgs_with_links.csv'
